AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.

Parameters:
  SourceEmail:
    Type: String
    Description: The sending email address for notification emails.
    Default: aws@marek.rocks

  DestEmail:
    Type: String
    Description: The receiving email address for notification emails.
    Default: marek.kuczynski@gmail.com

  SendEmails: 
    Description: Set whether to send SES emails or not (default 'n'). 
    Default: 'n'
    Type: String
    AllowedValues: 
      - 'y'
      - 'n'

  StorePublicS3:
    Description: Store a JSON object of blogposts as a public S3 file (default 'n').
    Default: 'n'
    Type: String
    AllowedValues:
      - 'y'
      - 'n'

Resources:

  rssgetfeed:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: getfeed.handler
      Runtime: python3.8
      CodeUri: lambda-getfeed/
      Description: 'Retrieve RSS feeds and store them in DynamoDB'
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ses:SendEmail'
              Resource: '*'
        - ComprehendFullAccess
        - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
        - DynamoDBCrudPolicy:
            TableName: !Ref rssfeed
        - S3WritePolicy:
            BucketName: !Ref PublicJsonBucket
      MemorySize: 256
      Timeout: 20
      Environment:
        Variables:
          dynamo_region: !Ref 'AWS::Region'
          dynamo_table: !Ref rssfeed
          fromemail: !Ref SourceEmail
          toemail: !Ref DestEmail
          sendemails: !Ref SendEmails
          s3bucket: !Ref PublicJsonBucket
          storepublics3: !Ref StorePublicS3
          POWERTOOLS_SERVICE_NAME: rssgetfeed
          POWERTOOLS_TRACE_DISABLED: "false"
      Tracing: Active
      ReservedConcurrentExecutions: 50
      Layers: 
        - !Ref lambdalayer
        - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:2"

  rsscrawl:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: crawl.handler
      Runtime: python3.8
      CodeUri: lambda-crawl/
      Description: 'Retrieve RSS feeds and check files stored on S3'
      Policies:
        - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
        - DynamoDBReadPolicy:
            TableName: !Ref rssfeed
        - S3ReadPolicy:
            BucketName: !Ref PublicJsonBucket
      MemorySize: 256
      Timeout: 10
      Environment:
        Variables:
          dynamo_region: !Ref 'AWS::Region'
          dynamo_table: !Ref rssfeed
          s3bucket: !Ref PublicJsonBucket
          storepublics3: !Ref StorePublicS3
          POWERTOOLS_SERVICE_NAME: rsscrawl
          POWERTOOLS_TRACE_DISABLED: "false"
      Tracing: Active
      ReservedConcurrentExecutions: 1
      Layers: 
        - !Ref lambdalayer
        - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:2"

  lambdalayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: rsslayer
      Description: python3 dependencies for XRay, BeautifulSoup4, feedparser and requests
      ContentUri: lambda-layer/
      CompatibleRuntimes:
        - python3.8
      LicenseInfo: 'MIT-0'
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.8

  rssfeed:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
      - AttributeName: blogsource
        AttributeType: S
      - AttributeName: timest
        AttributeType: S
      - AttributeName: visible
        AttributeType: S
      KeySchema:
      - AttributeName: blogsource
        KeyType: HASH
      - AttributeName: timest
        KeyType: RANGE  
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
      - IndexName: timest
        KeySchema:
        - AttributeName: visible
          KeyType: HASH
        - AttributeName: timest
          KeyType: RANGE
        Projection:
          ProjectionType: ALL

  rssblog:
    Type: AWS::Logs::LogGroup

  PublicJsonBucket:
    Type: AWS::S3::Bucket

  # state machine to coordinate the workflow
  blogstatemachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: STANDARD
      Tracing:
        Enabled: true
      DefinitionUri: statemachine/rssblog.asl.json
      DefinitionSubstitutions:
        rsscrawl: !GetAtt rsscrawl.Arn
        rssgetfeed: !GetAtt rssgetfeed.Arn
      Policies: 
        - LambdaInvokePolicy:
            FunctionName: !Ref rsscrawl
        - LambdaInvokePolicy:
            FunctionName: !Ref rssgetfeed
        - CloudWatchFullAccess
      Logging:
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt rssblog.Arn

# print the url of the state machine
Outputs:
  StateMachineURL:
    Value: !Sub 'https://${AWS::Region}.console.aws.amazon.com/states/home?region=${AWS::Region}#/statemachines/view/${blogstatemachine}'