AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.

Parameters:
  SourceEmail:
    Type: String
    Description: The sending email address for notification emails
    Default: aws@marek.rocks

  DestEmail:
    Type: String
    Description: The receiving email address for notification emails
    Default: marek.kuczynski@gmail.com

  SendEmails: 
    Description: Set whether to send SES emails or not (default disabled). 
    Default: 'n'
    Type: String
    AllowedValues: 
      - 'y'
      - 'n'

Resources:
  rssdynamo:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: dynamo.handler
      Runtime: python3.8
      CodeUri: lambda-dynamo/
      Description: 'Retrieve RSS feeds and store them in DynamoDB'
      Policies:
        - ComprehendFullAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref rssfeed
      MemorySize: 3008
      Timeout: 60
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(10 minutes)
      Environment:
        Variables:
          dynamo_region: !Ref 'AWS::Region'
          dynamo_table: !Ref rssfeed
          fromemail: !Ref SourceEmail
          toemail: !Ref DestEmail
          sendemails: !Ref SendEmails
      Tracing: Active
      ReservedConcurrentExecutions: 3
      Layers: 
        - !Ref lambdalayer
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Type: Lambda
            Destination: !GetAtt rssemail.Arn

  lambdalayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: rsslayer
      Description: Dependencies for XRay, BeautifulSoup4, feedparser and requests
      ContentUri: lambda-layer/
      CompatibleRuntimes:
        - python3.8
      LicenseInfo: ''
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.8

  rssemail:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda.handler
      Runtime: python3.8
      CodeUri: lambda-email/
      Description: 'Send an email with the AWS blog summary'
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ses:SendEmail'
              Resource: '*'
      MemorySize: 512
      Timeout: 10
      Tracing: Active
      ReservedConcurrentExecutions: 3

  rssfeed:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
      - AttributeName: source
        AttributeType: S
      - AttributeName: timest
        AttributeType: S
      - AttributeName: allts
        AttributeType: S
      - AttributeName: guid
        AttributeType: S
      KeySchema:
      - AttributeName: source
        KeyType: HASH
      - AttributeName: timest
        KeyType: RANGE  
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
          Enabled: true
          AttributeName: ttl
      GlobalSecondaryIndexes:
      - IndexName: allts
        KeySchema:
        - AttributeName: allts
          KeyType: HASH
        - AttributeName: guid
          KeyType: RANGE
        Projection:
          ProjectionType: KEYS_ONLY
