template-file-path: template.yaml

parameters:
  SourceEmail: "aws@marek.rocks"
  DestEmail: "marek.kuczynski@gmail.com"
  SendEmails: "y"
  CreateAppSync: "y"

tags:
  application: rss-lambda
  managed-by: cloudformation-git-sync
  environment: production
